# Generated by Django 4.1.3 on 2024-10-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academica', '0002_docente'),
    ]

    operations = [
        migrations.CreateModel(
            name='materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=75)),
                ('uv', models.CharField(max_length=2)),
            ],
        ),
    ]
